version: "3.7"

services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api_core_backend
    command: mvn test
    ports:
      - "8080:8080"
    links:
      - postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:latest"
    container_name: postgres_core_backend
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root