name: run_core_backend

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build And Run Docker Environment
        run: docker-compose up -d