name: run_core_backend

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Docker things
        run: |
          docker-compose up -d

      - name: Test with Maven
        run: |
          mvn test

      - name: Upload Coverage Raport from Jacoco to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          mvn jacoco:report
          cd target && cd site && cd jacoco
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r jacoco.xml
